include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    unnecessary_late: true
    use_key_in_widget_constructors: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
